<?php 
if($this->search){
	$startsWith = " starts with '{$this->search}'";
}
if($this->page > 1){
	$pageText = " - Page {$this->page}";
}
$title = "Browse lyricists{$startsWith}{$pageText}| LyricsRead.com";
$this->headTitle($title);

$description = 'List of lyricists: ';
?>
<div class="songHeader">
	<h1>Browse lyricists<?php echo $startsWith;?><?php echo $pageText;?></h1>
</div>
<div class="listSearch">
	<input type="text" id="lyricist_name"
			name="lyricist_name" value="Search lyricists.."
			store="<?php echo $this->lyricistStore?>" class="autocomplete"
			idfield="lyricist_id" 
			autotype="lyricist" /> 
	<input type="hidden" id="lyricist_id" name="lyricist_id" value="" />
</div>
<div class="clear"></div>
<div class="listContainer">
<?php if ($this->paginator && count($this->paginator)): ?>
	<div class="listRow">
	<?php foreach ($this->paginator as $key => $lyricist):	?>
	<?php
	$lyricistLink = strtolower($lyricist->getLyricistName()). ' songs.html';
	$filter  = new Zend_Filter_Word_SeparatorToDash();
	$lyricistLink = $filter->filter($lyricistLink);

	$lyricistLink = $this->serverUrl() . '/lyricist/'.$lyricistLink;
	if($key > 0 && $key % 4 == 0){
		echo '</div><div class="listRow">';
	}
	if($key < 10){
		if($key > 0){
			$description.= '| ';	
		}
		$description.= $lyricist->getLyricistName();
	}
	?>

		<div class="column">
		<?php
		$imageSrc = $lyricist->getImage();
		$imageSrc = empty($imageSrc) ? '/img/lyricist/_0_a3.jpg' : $imageSrc;
		?>
			<a href="<?php echo $lyricistLink?>"><img src="<?php echo $imageSrc?>"
				alt="<?php echo $lyricist->getLyricistName();?> songs" 
				title="<?php echo $lyricist->getLyricistName();?> songs" 
				width="100" height="100" /> </a>
			<div class="listLinkContainer">
				<a href="<?php echo $lyricistLink?>" title="<?php echo $lyricist->getLyricistName();?> songs"><?php echo $lyricist->getLyricistName();?>
				</a>
			</div>
		</div>

		<?php endforeach; ?>
	</div>
<?php else:?>
<?php echo $this->render('app-site/no_items.phtml')?>
<?php endif;?>
<div class="clear"></div>	
</div>
<?php echo $this->paginationControl($this->paginator,
                                    'Jumping',
                                    'shared/pagination_control.phtml'); ?>
<?php 
echo $this->render('app-site/social_button.phtml');
//Zend_Debug::dump($description);
$keywords = 'list of lyricists,list of song writers,list of poets,poets,song writers,lyricists,lyrics,collection of lyrics,find lyrics,find lyricists,find poets';

$this->headMeta()->appendName('keywords', $keywords);
$this->headMeta()->appendName('description', $description);
?>