<div class="itemsNav">
<span><a href="<?php echo $this->adminPath?>/trailer/add">New Trailer</a></span>
</div>
<?php echo $this->render('shared/search.phtml')?>
<table class="admin-dt">
	<thead>
		<tr>
			<th  width="5%">Select</th>
			<th>Trailer</th>
			<th>Album</th>	
			<th width="10%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $trailer):	?>
			<tr>
				<td>
					<div class="checkboxControl">
						<div class="fieldControl">
						<input name="trailer_select" type="checkbox" value="<?php echo $this->escape($trailer->getTrailerId()) ?>" />
						</div>
					</div>	
				</td>
				<td><?php echo $this->escape($trailer->getTrailerTitle()) ?></td>
				<td><?php echo $this->escape($trailer->getAlbum()->getAlbumName()) ?></td>
				<td><a href="<?php echo $this->adminPath?>/trailer/edit/trailer_id/<?php echo $this->escape($trailer->getTrailerId()) ?>"><img src="/img/icons/transparent.gif" class="admin_icons view_edit" alt="Edit" title="Click to edit"></a></td>				
				<td><a href="<?php echo $this->adminPath?>/trailer/published/trailer_id/<?php echo $this->escape($trailer->getTrailerId()) ?>/published/<?php echo $this->escape(!$trailer->getPublished()) ?>">
				<?php if ($this->escape($trailer->getPublished())): ?>				
					<img src="/img/icons/transparent.gif" class="admin_icons view_publish" alt="Published" title="Published | Click to toggle" />
				<?php else: ?>
					<img src="/img/icons/transparent.gif" class="admin_icons view_unpublish" alt="Unpublished" title="Unpublished | Click to toggle" />					
				<?php endif;?></a></td>								
	        </tr>	        
	        <?php endforeach; ?>
	        <tr>
	        	<td ><img class="selectallarrow" src="/img/icons/arrow_ltr.png" alt="With selected:"></td>
	        	<td colspan="4">
	        		<a href="#" onclick="cQuery.markAllRows('trailer_select'); return false;">Check All</a>&nbsp;|
	        		<a href="#" onclick="cQuery.unMarkAllRows('trailer_select'); return false;">Uncheck All</a>	        		
	        		<form method="post" class="adminViewForm" action="<?php echo $this->adminPath?>/trailer/update-many" onsubmit="return cQuery.adminViewFormValidate('trailer');">
	        			<input type="hidden" id="trailer_selected" name="trailer_selected" value="">						
						<select name="select_action" id="select_action">
							<option value="">--Select Action--</option>
							<option value="published__1">Publish</option>
							<option value="published__0">Unpublish</option>							
						</select>						 
					<button id="submit" class="adminButton" type="submit">
							<span>Update</span>
						</button>

					</form>
				</td>
	        </tr>
	        	
		<?php else: ?>
		<tr>
			<td colspan="5">There are no trailers to display</td>
		</tr>
		<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'shared/pagination_control.phtml'); ?>
<br/>