<div class="policy">
	<div class="policyHeader">
		<h1>Privacy policy</h1>
	</div>
	<div class="policyContent">
		<p>Last modified: Oct 8, 2012</p>
		<p>LyricsRead.com is committed to respecting and protecting your
			privacy. Should you choose to provide your Email address or any other
			personal information on any of the forms found on our site, you can
			be assured that it will only be used to support your relationship
			with LyricsRead.com. This privacy policy is intended for all users of
			LyricsRead.com.</p>
		<p>By visiting this web site you agree to be bound by the terms and
			conditions of this Privacy Policy. If you do not agree please do not
			use or access our services.</p>
		<p>In this privacy policy, you will find information on these areas:</p>
		<ol>
			<li>What personally identifiable information LyricsRead.com collects.</li>
			<li>What personally identifiable information third parties collect
				through the Web site.</li>
			<li>How LyricsRead.com uses the information.</li>
			<li>With whom LyricsRead.com may share user information.</li>
			<li>What choices are available to users regarding collection, use and
				distribution of the information.</li>
			<li>What types of security procedures are in place to protect the
				loss, misuse or alteration of information under LyricsRead.com
				control.</li>
			<li>How users can correct any inaccuracies in the information.</li>
			<li>If users have questions or concerns regarding this statement,
				they should contact <a href="mailto:webmaster@lyricsread.com"
				title="Contact us">LyricsRead.com.</a></li>
			<li>Any violation of this privacy policy will lead to suspension of
				use privileges and permanent removal from this web site.</li>
		</ol>
		<h2>Information Collection and Use</h2>
		<p>LyricsRead.com is the sole owner of the information collected on
			our site. LyricsRead.com collects and monitors information from our
			users at several different points on our Web site.</p>
		<h2>Registration</h2>
		<p>In order to use certain features of this site, a user must first
			complete the registration form. During registration a user is
			required to give contact information (such as name and email
			address). We use this information to contact the user, if necessary.
			Please safeguard your personal information. You may be liable for
			unauthorized use of our web site, as well as have your private
			information used by others.</p>
		<p>Unless you opt-out, you give LyricsRead.com permission to use your
			information as per this privacy policy.</p>
		<p>While LyricsRead.com will make every effort possible to protect
			your privacy, we do not promise, nor should you expect, that your
			personally identifiable information or private communications will
			always remain private. This will include parties who attempt to
			illegally enter our web site and intercept or access transmissions or
			private communications.</p>
		<p>Unless described otherwise in this privacy policy, we will not sell
			any information. All information collected will be used solely by
			LyricsRead.com to deliver targeted newsletters and advertisements.</p>
		<h2>Information Use</h2>
		<h3>Profile</h3>
		<p>We store information that we collect through cookies, log files
			and/or third parties to create a profile of our users. A profile is
			stored information that we keep on individual users that details
			their viewing preferences. Consequently, collected information is
			tied to the users personally identifiable information to provide
			offers and improve the content of the site for the user. This profile
			is used to tailor a user's visit to our Web site, and to direct
			pertinent marketing promotions to them. We do not share your profile
			with other third parties, unless specifically mentioned in this
			agreement.</p>
		<h3>Cookies</h3>
		<p>A cookie is a piece of data stored on the user's computer tied to
			information about the user. We may use both session ID cookies and
			persistent cookies. For the session ID cookie, once users close the
			browser, the cookie simply terminates. A persistent cookie is a small
			text file stored on the user's hard drive for an extended period of
			time. Persistent cookies can be removed by following Internet browser
			help file directions.</p>
		<p>Cookies, if used, will be used on our site to remember and recall
			login names, login information, previous purchases, potential
			purchases, as well as other items to help us better understand user's
			needs. By setting a cookie on our site, users would not have to log
			in a password more than once, thereby saving time while on our site.
			If users reject the cookie, they may still use our site. The only
			drawback to this is that the user will be limited in some areas of
			our site. Persistent cookies enable us to track and target the
			interests of our users to enhance the experience on our site. See the
			(Profile) section.</p>
		<p>We have no control over any third party use also use cookies to
			store personal information. However, we do not provide this
			information to any third party.</p>
		<h3>Log Files</h3>
		<p>Like most standard Web site servers we may use log files. This
			includes internet protocol (IP) addresses, browser type, internet
			service provider (ISP), referring/exit pages, platform type,
			date/time stamp, and number of clicks to analyze trends, administer
			the site, track user's movement in the aggregate, and gather broad
			demographic information for aggregate use. IP addresses, etc. are not
			linked to personally identifiable information.</p>
		<h2>Special Offers and Updates</h2>
		<p>We send all new members a welcoming email for your information, and
			if applicable, verify password and username. Out of respect for the
			privacy of our users we present the option to not receive these types
			of communications. Please see the Choice and Opt-out sections.</p>
		<h2>Newsletter</h2>
		<p>We will be sending a newsletter to all registered users. If a user
			wishes to subscribe to our newsletter, we ask for contact information
			such as name and email address. Out of respect for our users privacy
			we provide a way to opt-out of these communications.</p>
		<h2>Service Announcements</h2>
		<p>On rare occasions it is necessary to send out a strictly service
			related announcement. For instance, if our service is temporarily
			suspended for maintenance we might send users an email. Generally,
			users may not opt-out of these communications, though they can
			deactivate their account. However, these communications are not
			promotional in nature.</p>
		<h2>Customer Service</h2>
		<p>We communicate with users on a regular basis to provide requested
			services and in regards to issues relating to their account we reply
			via email or phone, in accordance with the users wishes.</p>
		<h3>Other uses</h3>
		<p>We can use your information to help facilitate requested
			information, resolve disputes, troubleshoot problems, enforce user
			agreements, analyze site usage, as well as site content
			customization, layout and services. Your information, such as your
			user ID and e-mail address, can be used with message boards and
			instant messaging. No personal information will be used here though.</p>
		<h3>End of services</h3>
		<p>LyricsRead.com will not store any user information, other than
			e-mail, when a user no longer wishes to subscribe to the services
			offered.</p>
		<h2>Legal Disclaimer</h2>
		<p>Though we make every effort to preserve user privacy, we may need
			to disclose personal information when required by law wherein we have
			a good-faith belief that such action is necessary to comply with a
			current judicial proceeding, a court order or legal process served on
			our Web site. This includes, but is not limited to, any defense to
			any claim in which LyricsRead.com is a defendant, to assist in any
			investigations by law enforcement agencies, or violations of any
			LyricsRead.com policy.</p>
		<h2>Aggregate Information (non-personally identifiable)</h2>
		<p>While LyricsRead.com will not rent, sell or share your information
			in general, there are certain instances that your information may be
			used. We share aggregated demographic information and in some cases
			your e-mail address with others. This is how your information will be
			shared:</p>
		<p>-Information relating to minors will only be used with prior
			parental or guardianship approval.</p>
		<p>-If LyricsRead.com merges with another company, then this
			information will be shared with the merging company.</p>
		<strong>These are the instances in which we will share users' personal
			information:</strong>

		<p>LyricsRead.com does not rent, sell, or share personal information
			about you with other people or nonaffiliated companies except under
			the following circumstances: We respond to court orders,
			or legal process, or to establish or exercise our legal rights or
			defend against legal claims;</p>
		<p>We believe it is necessary to share information in order to
			investigate, prevent, or take action regarding illegal activities,
			suspected fraud, situations involving potential threats to the
			physical safety of any person, violations of LyricsRead.com's terms
			of use, or as otherwise required by law;</p>
		<p>We transfer or lease information about you if LyricsRead.com is
			acquired by or merged with another company. In this event,
			LyricsRead.com will notify you before information about you is
			transferred and becomes subject to a different privacy policy;</p>
		<p>We do not support any illegal use of your private information and
			will make every effort to stop such practices in order to protect
			your privacy.</p>
		<h2>Business Transitions</h2>
		<p>In the event LyricsRead.com goes through a business transition,
			such as a merger, being acquired by another company, or selling a
			portion of its assets, users' personal information will, in most
			instances, be part of the assets transferred. Users will be notified
			via e-mail, as well as with a prominent notice on our Web site for at
			least 30 days prior to a change of ownership or control of their
			personal information. If as a result of the business transition, the
			users' personally identifiable information will be used in a manner
			different from that stated at the time of collection they will be
			given choice consistent with our notification of changes section.</p>
		<h2>Children's privacy</h2>
		<p>At LyricsRead.com, we also treasure the safety of children under
			the age of thirteen. We will never knowingly collect a child's
			personal information, including name, email address or any other
			information. Children under the age of thirteen are not allowed to
			register for our services without parental consent. If any child
			under the age of thirteen submits personal information without
			parental consent through the registration process, that information
			will be immediately expunged from our database. If you have any
			knowledge of children under the age of thirteen using the web site
			improperly, please let us know immediately.</p>
		<h2>Choice/Opt-out</h2>
		<p>Our users are given the opportunity to -opt-out- of having their
			information used for purposes not directly related to our site at the
			point where we ask for information. Users of our site are always
			notified when their information is being collected by any outside
			parties. We do this so our users can make an informed choice as to
			whether or not they should proceed with services that require an
			outside party.</p>
		<h2>Links</h2>
		<p>This Web site may contain links to other sites. Please be aware
			that we, LyricsRead.com, are not responsible for the privacy
			practices of such other sites. We encourage our users to be aware
			when they leave our site and to read the privacy statements of each
			and every Web site that collects personally identifiable information.
			This privacy statement applies solely to information collected by
			this Web site. LyricsRead.com may have co-branding and/or framing
			relations with other companies. In this case, you should be familiar
			with the privacy policies of both companies, since you may be subject
			to each of them.</p>
		<h2>Surveys & Contests</h2>
		<p>From time-to-time our site requests information from users via
			surveys or contests. Participation in these surveys or contests is
			completely voluntary but the information collected may be disclosed
			as per this privacy agreement. The requested information typically
			includes contact information (such as name and shipping address), and
			demographic information (such as zip code). Contact information will
			be used/shared with the contest/survey sponsors (if any) to notify
			the winners and award prizes. Survey information will be used for
			purposes of monitoring or improving the use and satisfaction of this
			site. Unless mentioned in this privacy policy, users' personally
			identifiable information is not shared with third parties unless we
			give prior notice and choice. Though we may use an intermediary to
			conduct these surveys or contests, they may not use users' personally
			identifiable information for any secondary purposes.</p>
		<h2>Tell-A-Friend</h2>
		<p>We may be starting a referral program. If a user elects to use our
			referral service for informing a friend about our site, we ask them
			for the friend's name and email address. LyricsRead.com will
			automatically send the friend a one-time email inviting them to visit
			the site. LyricsRead.com stores this information for the sole purpose
			of sending this one-time email and tracking the success of our
			referral program.</p>
		<p>LyricsRead.com can not be liable for the actions of any -friend-
			who may give out your personal information, other than what is
			permitted in this privacy policy. Any abuse of this service will lead
			to suspension or termination of use of this website.</p>
		<h2>Security</h2>
		<p>This Web site takes every precaution to protect our users'
			information. When users submit information via the Web site, their
			information is protected both online and off-line. However, LyricsRead.com can't be liable (for any damages whatsoever)
			for security breaches that occur outside of LyricsRead.com.</p>
		<p>
			If users have any questions about the security at our Web site, users
			can <a href="mailto:webmaster@lyricsread.com" title="Contact us">contact
				us here</a>.
		</p>
		<h2>Correcting/Updating/Deleting/Deactivating Personal Information</h2>
		<p>If a user's personally identifiable information changes (such as
			zip code, phone, email or postal address), or if a user no longer
			desires our service, we provide a way to correct, update or
			delete/deactivate users' personally identifiable information. This
			can usually be done on line with LyricsRead.com, or by emailing our
			Customer Support.</p>
		<h2>Notification of Changes</h2>
		<p>If we decide to change our privacy policy, we will post those
			changes to this privacy statement, the homepage, and other places we
			deem appropriate so our users are always aware of what information we
			collect, how we use it, and under what circumstances, if any, we
			disclose it. We will use information in accordance with the privacy
			policy under which the information was collected.</p>
		<p>If, however, we are going to use users' personally identifiable
			information in a manner different from that stated at the time of
			collection we will notify users via email. Users will have a choice
			as to whether or not we use their information in this different
			manner. However, if users have opted out of all communication with
			the site, or deleted/deactivated their account, then they will not be
			contacted, nor will their personal information be used in this new
			manner. In addition, if we make any material changes in our privacy
			practices that do not affect user information already stored in our
			database, we will post a prominent notice on our Web site notifying
			users of the change. In some cases where we post a notice we will
			also email users, who have opted to receive communications from us,
			notifying them of the changes in our privacy practices.</p>
		<h2>Contact Information</h2>
		<p>
			If users have any questions, disputes or suggestions regarding our
			privacy policy, please <a href="mailto:webmaster@lyricsread.com"
				title="Contact us">contact us here</a>.
		</p>
	</div>
</div>
