<div class="policy">
	<div class="policyHeader">
		<h1>Terms of use</h1>
	</div>
	<div class="policyContent">
		<p>Last modified: Oct 8, 2012</p>
		<h2>Introduction</h2>
		<p>Welcome to LyricsRead.com (the "Website").</p>
		<p>Please read these terms of use ("TOU") before accessing the
			Website. As a result of your access and use of the Website, you
			hereby agree to the TOU, conditions and notices set out herein. If
			you do not agree, we request and advise that you not use the Website.
			We reserve the right to revise the TOU from time to time. Please
			check back to the TOU periodically to review any changes. Your
			continued access to and use of the Website will indicate your
			acceptance of any such changes. We may, at any time, modify or
			discontinue all or part of the Website; charge, modify or waive fees
			in connection with any use of the Website; or offer opportunities to
			some or all Website users.</p>
		<p>
			Your use of the Website is also governed by our <a
				href="<?php echo $this->serverUrl().'/privacy/'?>"
				title="Privacy policy">Privacy Policy</a> and subject to all
			applicable laws and regulations.
		</p>
		<h2>Terms of Use</h2>
		<p>The Website provide Website users with Content and Services (as
			defined below), subject to this TOU.</p>
		<h2>Content and Services</h2>
		<p>The Website currently provides Website users with access to music
			lyrics and music information, including albums, artists, singers,
			composers, lyricists, images and video and audio footage
			(collectively, the "Content"). The Website also currently provides
			Website users with various services and other interactive and
			non-interactive features (collectively, the "Services").</p>
		<p>The Website, Content and Services are all subject to the TOU. You
			acknowledge and agree that the Website, Content and Services are
			provided on an "as is" and "as available" basis and that WE(the
			owner, developers and editors or anyone else associated with the
			development and maintenance of the website) do not accept any
			responsibility in connection with your use of or inability to use the
			Website, Content or Services. All music, lyrics, albums, videos, and
			pictures found on LyricsRead.com are, and remain, copyright and
			property of their respective owners. All lyrics provided for
			educational purposes only and no infringement whatsoever is intended.</p>
		<p>The Website, Content and Services are provided for personal use
			only and are not to be used by you for any commercial purpose.</p>
		<h2>Access to Services</h2>
		<p>As a condition to your use of certain Services, you will be
			required to provide the following information in respect of yourself.
			You agree that any information you provide will be accurate and
			complete.</p>
		<h2>Ability to Enter Into This Agreement</h2>
		<p>By accessing or using the Website, you affirm that you are of legal
			age to enter into this TOU or, if you are not, that you have obtained
			parental or guardian consent to enter into this TOU.</p>
		<h2>Information Collected From Users</h2>
		<p>
			All information collected from you will be used and maintained in
			accordance with our <a
				href="<?php echo $this->serverUrl().'/privacy/'?>"
				title="Privacy policy">Privacy Policy</a>.
		</p>
		<h2>User Conduct</h2>
		<p>You agree that in using the Website, Content or Services you will
			not upload, post of otherwise make available any Content that is
			unlawful, threatening, abusive, harassing, defamatory, tortious,
			vulgar, obscene, invasive of another's privacy, hateful,
			intentionally false, inaccurate or misleading or is otherwise
			objectionable;infringes any patent, trademark, trade secret,
			copyright or other intellectual property or proprietary right of any
			person;is unauthorized or unsolicited advertising, promotional
			materials, "junk mail", "spam", "chain letters" or any other form of
			unauthorized solicitation; contains software viruses or any other
			form of computer code that is designed to disrupt or damage the
			functionality of any software, hardware or telecommunications
			equipment; or violates any applicable local, provincial, national or
			international law.</p>
		With respect to the uploading of Content by users, you are hereby
		advised that WE may, but have no obligation to, monitor such Content
		for accuracy, completeness and appropriateness, before or after such
		Content appears on the Website.
		</p>
		<h2>Your Content in our Services</h2>
		<p>With respect to any Content you upload, post or otherwise make
			available in the course of using the Website, Content or Services,
			including without limit any music lyrics, you:</p>

		<ol>
			<li>acknowledge and agree that you give LyricsRead.com and its
				designees in respect of any such Content a perpetual, royalty-free,
				sub-licensable (through multiple tiers), non-exclusive, worldwide,
				irrevocable right and license to use, reproduce, display, publish,
				modify, adapt, transmit and distribute any such Content in any form,
				anywhere and for any purpose;</li>
			<li>represent and warrant that you own, or otherwise have the right
				to exploit, such Content and to grant the rights that you grant to
				lyricsread.com herein; and</li>
			<li>that the hosting and other use of your Content by lyricsread.com
				in accordance with the rights granted by you to the Website
				hereunder will not infringe or violate the intellectual property
				rights or other rights of any third party.</li>
		</ol>
		<h2>Notice to Copyright Holders</h2>
		<p>The Website, Content and Services are provided for personal use
			only and are not used for any commercial purpose. No infringement
			whatsoever is intended</p>
		<p>
			If you hold copyright(s) (or any other proprietary right(s)) to any
			Content, including without limit music lyrics, made available via the
			Website, and have any questions or concerns about the licensing,
			accuracy, or possible take-down of such Content from the Website,
			please <a href="mailto:webmaster@lyricsread.com" title="Contact us">contact
				us here</a>
		</p>
		<h2>Indemnity</h2>
		<p>You agree to defend, indemnify and hold harmless LyricsRead.com and
			any of its affiliates, employees, officers, directors, agents,
			representatives, licensees, successors and assigns from all
			liabilities, claims and expenses, including reasonable legal fees and
			disbursements, arising in connection with (a) your access to, use of
			or activities in connection with the Website, Content or Services;
			(b) any violation by you of the TOU; or (c) any claim that any
			Content uploaded, posted or otherwise made available by you in
			connection with the Website, or any use or exploitation thereof,
			infringed upon or violated the rights of any third party.</p>
		<h2>Linking</h2>
		<p>The Website or Services may provide, or third parties may provide,
			links to other internet sites or resources. LyricsRead.com has no
			control over other internet sites and resources and as such you
			acknowledge and agree LyricsRead.com is not responsible for the
			availability of such external internal sites or resources, and does
			not endorse and are not responsible or liable for any Content,
			advertising, products, or other materials on or available from such
			sites or resources. You further acknowledge and agree that
			LyricsRead.com shall not be responsible or liable, directly or
			indirectly, for any damage or loss caused or alleged to be caused by
			or in connection with use of or reliance on any such Content, goods
			or Services available on or through any such site or resource.</p>
		<h2>Our Warranties and Disclaimers</h2>
		<p>You expressly understand and agree that:</p>
		<p>LyricsRead.com expressly disclaims all warranties of any kind,
			whether express or implied, including, but not limited to the implied
			warranties of merchantability, fitness for a particular purpose and
			non-infringement. Lyricsread.com does not make any warranty that:</p>
		<ol>
			<li>the website, services or the content will meet your requirements;</li>
			<li>the website, the services or the content will be uninterrupted,
				timely, secure, or error-free;</li>
			<li>the results that may be obtained from your use of the website,
				the services or the content will be accurate or reliable;</li>
			<li>the quality of any products, services, information, or other
				material purchased or obtained by you through the website, the
				services or the content will meet your expectations; and</li>
			<li>any errors in the software operating on the website will be
				corrected.</li>
			<li>any material downloaded or otherwise obtained through the use of
				the website or the services is done at your own discretion and risk
				and that you will be solely responsible for any damage to your
				computer system or loss of data that results from the download of
				any such material.</li>
			<li>no advice or information, whether oral or written, obtained by
				you from the website or through or from the services or the content
				shall create any warranty not expressly stated in the tou.</li>
		</ol>
		<h2>Liability for our Services</h2>
		<p>You expressly understand and agree that LyricsRead.com shall not be
			liable for any direct, indirect, incidental, special, consequential
			or exemplary damages, including, but not limited to, damages for loss
			of profits, goodwill, use, data or other intangible losses (even if
			the entities have been advised of the possibility of such damages),
			resulting from:</p>
		<ol>
			<li>the use or the inability to use the website, the services or the
				content;</li>
			<li>the cost of procurement of substitute goods and services
				resulting from any goods, data, information or services purchased or
				obtained or messages received or transactions entered into through
				or from the website, the services or the content;</li>
			<li>unauthorized access to or alteration of your transmissions or
				data;</li>
			<li>statements or conduct of any third party on the website, the
				services or in the content; or</li>
			<li>any other matter relating to the website, the services or the
				content.</li>
		</ol>
		<!-- 
		<h2>Exclusions and limitations</h2>
		<p>Some jurisdictions do not allow the exclusion of certain warranties or
		the limitation or exclusion of liability for incidental or
		consequential damages. Accordingly, some of the above limitations of
		under disclaimer of warranties and limitation of liability may not
		apply to you.</p>
		  
		<h2>Website design copyrights</h2>
		<p> The design(User Interface) of
		this website is an exclusive intellectual property of LyricsRead.com.
		So you are not allowed to adapt this look(USER INTERFACE) or modify it
		in any way. We advise you to not to use any code(HTML,
		stylesheets(CSS) or anything else).</p>
		-->
	</div>
</div>
