<?php 
if($this->search){
	$startsWith = " starts with '{$this->search}'";
}

if($this->page > 1){
	$pageText = " - '{$this->page}'";
}

$title = "Browse trailers{$startsWith}{$pageText}| LyricsRead.com";
$this->headTitle($title);

$keywords = 'list of trailers,list of movies,movies,songs,lyrics,collection of lyrics,find lyrics';
$description = 'List of trailers: ';
?>
<div class="songHeader">
	<h1>Browse trailers<?php echo $startsWith;?><?php echo $pageText;?></h1>
</div>
<div class="clear"></div>
<div class="listContainer">
<?php if ($this->paginator && count($this->paginator)): ?>
	<div class="listRow">
	<?php foreach ($this->paginator as $key => $trailer):	?>
	<?php
	$trailerLink = strtolower($trailer->getTrailerTitle()). '.html';
	$filter  = new Zend_Filter_Word_SeparatorToDash();
	$trailerLink = $filter->filter($trailerLink);

	$trailerLink = $this->serverUrl(). '/trailer/'.$trailerLink;
	if($key > 0 && $key % 4 == 0){
		echo '</div><div class="listRow">';
	}
	
	?>

		<div class="column">
		<?php
		$imageSrc = $trailer->getAlbum()->getImage();
		$imageSrc = empty($imageSrc) ? '/img/album/default.png' : $imageSrc;
		?>
			<a href="<?php echo $trailerLink?>"><img src="<?php echo $imageSrc?>"
				alt="Watch <?php echo $trailer->getTrailerTitle();?>"
				title="Watch <?php echo $trailer->getTrailerTitle();?>" 
				width="100" height="100" /> </a>
			<div class="listLinkContainer">
				<a href="<?php echo $trailerLink?>" title="Watch <?php echo $trailer->getTrailerTitle();?>"><?php echo $trailer->getTrailerTitle();?>
				</a>
			</div>
		</div>

		<?php endforeach; ?>
	</div>
<?php else:?>
<?php echo $this->render('app-site/no_items.phtml')?>
<?php endif;?>
<div class="clear"></div>	
</div>
<?php echo $this->paginationControl($this->paginator,
                                    'Jumping',
                                    'shared/pagination_control.phtml'); ?>
<?php 
echo $this->render('app-site/social_button.phtml');
//Zend_Debug::dump($description);
$this->headMeta()->appendName('keywords', $keywords);
$this->headMeta()->appendName('description', $description);
?>
