<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;
charset=utf-8" />
<meta name="ROBOTS" content="NOINDEX, NOFOLLOW" />
<base href="/" />
<?php

$this->headLink()->appendStylesheet('/css/style.css')
->headLink()->appendStylesheet('/public/library/css/flick/jquery-ui-1.8.22.custom.css');
$this->headScript()->prependFile('/js/cquery.js')
->headScript()->prependFile('/public/library/js/jquery-ui-1.8.22.custom.min.js')
->headScript()->prependFile('/public/library/js/jquery-1.7.2.min.js');

echo $this->headTitle();
echo $this->headMeta();
echo $this->headStyle();
echo $this->headLink();

$onloadScript = "cQuery.init();";
$this->headScript()->appendScript($onloadScript);

?>
<link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico" />
<style>
.ui-autocomplete-loading {
	background: white
		url('library/css/flick/images/ui-anim_basic_16x16.gif') right center
		no-repeat;
}
</style>

</head>
<body>
	<div id="shell">
		<div id="page">
			<div id="header">
				<div id="logo">
					<a href="/"><img src="/img/logo.png" title="LyricsRead.com" alt="LyricsRead.com" /> </a>
				</div>
				<div id="logged-in-msg">
					Welcome,
					<?php echo $this->escape($this->username);?>
					 | 
					<a href='<?php echo $this->escape($this->urllogout);?>'>Logout</a>
				</div>
			</div>
			<div id="main">
			<?php if($this->escape($this->user->type) == 'admin'):?>
				<div id="mainA">
					<div class="aColumn">
						<div class="menu">
						<?php
							$partial = array('menu.phtml', 'default');
							$this->navigation()->menu()->setPartial($partial);
							echo $this->navigation()->menu()->render();						
						?>
						</div>
					</div>
					<div class="bcColumn">
						<div class="breadcrumbs">
						<?php echo $this->navigation()->breadcrumbs()->setRenderInvisible(true); ?>
						</div>

						<?php echo $this->layout()->content ?>
					</div>
				</div>
			<?php else :?>
				<?php echo $this->layout()->content ?>
			<?php endif;?>	
			</div>
			<div id="footer">
				<?php echo $this->layout()->render('footer')?>
			</div>
		</div>
	</div>
	<?php echo $this->headScript() ?>
	<script>
	
	</script>
</body>
</html>
