<div class="footer_top">
</div>
<div class="footer_bottom">
<span>&copy; copyright 2012 <a href="<?php echo $this->serverUrl().'/'?>" title="LyricsRead.com">LyricsRead</a></span>
|
<span><a href="<?php echo $this->serverUrl().'/terms/'?>" title="Terms of use">Terms of use</a></span>
|
<span><a href="<?php echo $this->serverUrl().'/privacy/'?>" title="Privacy policy">Privacy policy</a></span>
</div>
