<div class="right-ad">
	<div class="right-ad-item">
		<div
			style="_height: px; width: 336px; background-color: #FFFFFF; font-family: Arial; border: 1px solid #FFFFFF; text-align: left;">
			<a href="http://lyricsread.com/album/podaa-podi-songs.html"
				style="font-size: 22px; text-decoration: none; color: #87A800;">Podaa
				Podi</a> <a
				href="http://lyricsread.com/album/student-of-the-year-songs.html"
				style="font-size: 23px; text-decoration: none; color: #DE2159;">Student
				of the Year</a> <a
				href="http://lyricsread.com/album/kumki-songs.html"
				style="font-size: 22px; text-decoration: none; color: #039FAF;">Kumki</a>
			<a href="http://lyricsread.com/composer/ilaiyaraaja-songs.html"
				style="font-size: 14px; text-decoration: none; color: #87A800;">Ilaiyaraaja</a>
			<a href="http://lyricsread.com/album/maattrraan-songs.html"
				style="font-size: 22px; text-decoration: none; color: #FF7600;">Maattrraan</a>
			<a href="http://lyricsread.com/lyricist/kannadasan-songs.html"
				style="font-size: 19px; text-decoration: none; color: #039FAF;">Kannadasan</a>
			<a
				href="http://lyricsread.com/singer/s-p-balasubrahmanyam-songs.html"
				style="font-size: 17px; text-decoration: none; color: #DE2159;">S P
				Balasubrahmanyam</a> <a
				href="http://lyricsread.com/singer/shreya-ghoshal-songs.html"
				style="font-size: 18px; text-decoration: none; color: #039FAF;">Shreya
				Ghoshal</a> <a
				href="http://lyricsread.com/lyricist/pa-vijay-songs.html"
				style="font-size: 13px; text-decoration: none; color: #DE2159;">Pa
				Vijay</a> <a
				href="http://lyricsread.com/composer/harris-jayaraj-songs.html"
				style="font-size: 16px; text-decoration: none; color: #039FAF;">Harris
				Jayaraj</a> <a
				href="http://lyricsread.com/artist/dev-anand-songs.html"
				style="font-size: 16px; text-decoration: none; color: #87A800;">Dev
				Anand</a> <a
				href="http://lyricsread.com/lyricist/na-muthukumar-songs.html"
				style="font-size: 13px; text-decoration: none; color: #039FAF;">Na
				Muthukumar</a> <a
				href="http://lyricsread.com/album/rush-(2012)-songs.html"
				style="font-size: 23px; text-decoration: none; color: #DE2159;">Rush
				(2012)</a> <a
				href="http://lyricsread.com/composer/a-r-rahman-songs.html"
				style="font-size: 16px; text-decoration: none; color: #87A800;">A R
				Rahman</a> <a href="http://lyricsread.com/song/"
				style="font-size: 18px; text-decoration: none; color: #FF7600;">Songs</a>
			<a href="http://lyricsread.com/album/jab-tak-hai-jaan-songs.html"
				style="font-size: 22px; text-decoration: none; color: #87A800;">Jab
				Tak Hai Jaan</a> <a
				href="http://lyricsread.com/lyricist/anand-bakshi-songs.html"
				style="font-size: 16px; text-decoration: none; color: #039FAF;">Anand
				Bakshi</a> <a
				href="http://lyricsread.com/composer/yuvan-shankar-raja-songs.html"
				style="font-size: 14px; text-decoration: none; color: #87A800;">Yuvan
				Shankar Raja</a> <a
				href="http://lyricsread.com/lyricist/vaali-songs.html"
				style="font-size: 15px; text-decoration: none; color: #87A800;">Vaali</a>
			<a href="http://lyricsread.com/singer/"
				style="font-size: 13px; text-decoration: none; color: #87A800;">Singers</a>
			<a href="http://lyricsread.com/artist/rajinikanth-songs.html"
				style="font-size: 17px; text-decoration: none; color: #FF7600;">Rajinikanth</a>
			<a href="http://lyricsread.com/album/thuppakki-songs.html"
				style="font-size: 22px; text-decoration: none; color: #FF7600;">Thuppakki</a>
			<a href="http://lyricsread.com/lyricist/javed-akhtar-songs.html"
				style="font-size: 13px; text-decoration: none; color: #FF7600;">Javed
				Akhtar</a> <a href="http://lyricsread.com/artist/m-g-r-songs.html"
				style="font-size: 18px; text-decoration: none; color: #DE2159;">M G
				R</a> <a href="http://lyricsread.com/artist/"
				style="font-size: 15px; text-decoration: none; color: #87A800;">Artists</a>
			<a href="http://lyricsread.com/singer/shakira-songs.html"
				style="font-size: 13px; text-decoration: none; color: #FF7600;">Shakira</a>
			<a href="http://lyricsread.com/album/saattai-songs.html"
				style="font-size: 18px; text-decoration: none; color: #DE2159;">Saattai</a>
			<a href="http://lyricsread.com/sitemap.html"
				style="font-size: 15px; text-decoration: none; color: #FF7600;">Sitemap</a>
			<a href="http://lyricsread.com/composer/"
				style="font-size: 15px; text-decoration: none; color: #87A800;">Composers</a>
			<a
				href="http://lyricsread.com/album/neethane-en-ponvasantham-songs.html"
				style="font-size: 22px; text-decoration: none; color: #87A800;">Neethane
				En Ponvasantham</a> <a href="http://lyricsread.com/album/"
				style="font-size: 19px; text-decoration: none; color: #87A800;">Albums</a>
			<a href="http://lyricsread.com/lyricist/"
				style="font-size: 13px; text-decoration: none; color: #FF7600;">Lyricists</a>
			<a href="http://lyricsread.com/album/uyire-songs.html"
				style="font-size: 15px; text-decoration: none; color: #DE2159;">Uyire</a>
			<a href="http://lyricsread.com/trailer/"
				style="font-size: 16px; text-decoration: none; color: #FF7600;">Trailers/
				Teasers</a> <a
				href="http://lyricsread.com/album/aadhi-bhagavan-songs.html"
				style="font-size: 22px; text-decoration: none; color: #039FAF;">Aadhi
				Bhagavan</a> <a
				href="http://lyricsread.com/singer/chinmayi-songs.html"
				style="font-size: 15px; text-decoration: none; color: #87A800;">Chinmayi</a>
			<a href="http://lyricsread.com/"
				style="font-size: 14px; text-decoration: none; color: #DE2159;">Home</a>
		</div>
	</div>
</div>
