<div class="htlFormControl">
	<form id="artist-form" method="post" class="adminForm" action="<?php echo $this->adminPath?>/artist/save">

		<fieldset class="adminBlock">
			<div class="control">
				<h5 class="sectionHeader">Artist</h5>								
			</div>	
			<div class="control">
				<div class="labelControl">
					<label for="artist_name">Artist</label>
				</div>
				<div class="fieldControlLeft">
					<input type="hidden" id="overlay" name="overlay" value="<?php echo $this->overlay?>">
					<input type="text" id="artist_name" name="artist_name" value="">
				</div>
			</div>
			<div class="control">									
				<button id="artist_submit" class="adminButton" type="<?php echo $this->overlay == '1' ? 'button' : 'submit'?>" form-id="artist-form">
					<span>Create Artist</span>
				</button>						
			</div>
		</fieldset>

	</form>
</div>
