<div class="itemsNav">
<span><a href="<?php echo $this->adminPath?>/artist/add">New Artist</a></span>
</div>
<?php echo $this->render('shared/search.phtml')?>
<table class="admin-dt">
	<thead>
		<tr>
			<th  width="5%">Select</th>
			<th>Artist</th>
			<th width="10%"></th>
			<th width="10%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $artist):	?>
			<tr>
				<td>
					<div class="checkboxControl">
						<div class="fieldControl">
						<input name="artist_select" type="checkbox" value="<?php echo $this->escape($artist->getArtistId()) ?>" />
						</div>
					</div>	
				</td>
				<td><?php echo $this->escape($artist->getArtistName()) ?></td>
				<td><a href="<?php echo $this->adminPath?>/artist/edit/artist_id/<?php echo $this->escape($artist->getArtistId()) ?>"><img src="/img/icons/transparent.gif" class="admin_icons view_edit" alt="Edit" title="Click to edit"></a></td>
				<td><a href="<?php echo $this->adminPath?>/artist/photo/artist_id/<?php echo $this->escape($artist->getArtistId()) ?>/has_photo/<?php echo $this->escape(!$artist->getHasPhoto()) ?>">
				<?php if ($this->escape($artist->getHasPhoto())): ?>				
					<img src="/img/icons/transparent.gif" class="admin_icons view_has_photo" alt="Photo available" title="Photo available | Click to toggle">
				<?php else: ?>
					<img src="/img/icons/transparent.gif" class="admin_icons view_has_no_photo" alt="Photo not available" title="Photo not available | Click to toggle">					
				<?php endif;?></a></td>		
				<td><a href="<?php echo $this->adminPath?>/artist/lock/artist_id/<?php echo $this->escape($artist->getArtistId()) ?>/locked/<?php echo $this->escape(!$artist->getLocked()) ?>">
				<?php if ($this->escape($artist->getLocked())): ?>				
					<img src="/img/icons/transparent.gif" class="admin_icons view_lock" alt="Locked" title="Locked | Click to toggle" />
				<?php else: ?>
					<img src="/img/icons/transparent.gif" class="admin_icons view_unlock" alt="Unlocked" title="Unlocked | Click to toggle" />					
				<?php endif;?></a></td>							
	        </tr>	        
	        <?php endforeach; ?>
	        <tr>
	        	<td ><img class="selectallarrow" src="/img/icons/arrow_ltr.png" alt="With selected:"></td>
	        	<td colspan="4">
	        		<a href="#" onclick="cQuery.markAllRows('artist_select'); return false;">Check All</a>&nbsp;|
	        		<a href="#" onclick="cQuery.unMarkAllRows('artist_select'); return false;">Uncheck All</a>	        		
	        		<form method="post" class="adminViewForm" action="<?php echo $this->adminPath?>/artist/update-many" onsubmit="return cQuery.adminViewFormValidate('artist');">
	        			<input type="hidden" id="artist_selected" name="artist_selected" value="">						
						<select name="select_action" id="select_action">
							<option value="">--Select Action--</option>
							<option value="has_photo__1">Has photo</option>
							<option value="has_photo__0">Has no photo</option>
							<option value="locked__1">Lock</option>
							<option value="locked__0">Unlock</option>
						</select>						 
					<button id="submit" class="adminButton" type="submit">
							<span>Update</span>
						</button>

					</form>
				</td>
	        </tr>
	        	
		<?php else: ?>
		<tr>
			<td colspan="5">There are no artists to display</td>
		</tr>
		<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'shared/pagination_control.phtml'); ?>
<br/>