<?php 
if($this->search){
	$startsWith = " starts with '{$this->search}'";
}
if($this->page > 1){
	$pageText = " - Page {$this->page}";
}
$title = "Browse singers{$startsWith}{$pageText}| LyricsRead.com";
$this->headTitle($title);

$description = 'List of singers: ';
?>
<div class="songHeader">
	<h1>Browse singers<?php echo $startsWith;?><?php echo $pageText;?></h1>
</div>
<div class="listSearch">
	<input type="text" id="singer_name"
			name="singer_name" value="Search singers.."
			store="<?php echo $this->singerStore?>" class="autocomplete"
			idfield="singer_id"
			autotype="singer" /> 
	<input type="hidden" id="singer_id" name="singer_id" value="" />
</div>
<div class="clear"></div>
<div class="listContainer">
<?php if ($this->paginator && count($this->paginator)): ?>
	<div class="listRow">
	<?php foreach ($this->paginator as $key => $singer):	?>
	<?php
	$singerLink = strtolower($singer->getSingerName()). ' songs.html';
	$filter  = new Zend_Filter_Word_SeparatorToDash();
	$singerLink = $filter->filter($singerLink);

	$singerLink = $this->serverUrl() . '/singer/'.$singerLink;
	if($key > 0 && $key % 4 == 0){
		echo '</div><div class="listRow">';
	}
	if($key < 10){
		if($key > 0){
			$description.= '| ';	
		}
		$description.= $singer->getSingerName();
	}
	?>

		<div class="column">
		<?php
		$imageSrc = $singer->getImage();
		$imageSrc = empty($imageSrc) ? '/img/singer/_0_a3.jpg' : $imageSrc;
		?>
			<a href="<?php echo $singerLink?>"><img src="<?php echo $imageSrc?>"
				alt="<?php echo $singer->getSingerName();?> songs" 
				title="<?php echo $singer->getSingerName();?> songs" 
				width="100" height="100" /> </a>
			<div class="listLinkContainer">
				<a href="<?php echo $singerLink?>" title="<?php echo $singer->getSingerName();?> songs"><?php echo $singer->getSingerName();?>
				</a>
			</div>
		</div>

		<?php endforeach; ?>
	</div>
<?php else:?>
<?php echo $this->render('app-site/no_items.phtml')?>
<?php endif;?>
<div class="clear"></div>	
</div>
<?php echo $this->paginationControl($this->paginator,
                                    'Jumping',
                                    'shared/pagination_control.phtml'); ?>
<?php
echo $this->render('app-site/social_button.phtml');
//Zend_Debug::dump($description);
$keywords = 'list of singers,singers,lyrics,collection of lyrics,list of lyrics,find lyrics,find singers';

$this->doctype('XHTML1_RDFA'); 
$this->headMeta()->appendName('keywords', $keywords);
$this->headMeta()->appendName('description', $description);
$this->headMeta()->setProperty('og:site_name', $this->socialConfig['FACEBOOK']['OG_SITE_NAME']);
$this->headMeta()->setProperty('og:title', $musicTitle. ' song lyrics');
$this->headMeta()->setProperty('og:type', $this->socialConfig['FACEBOOK']['OG_SONG_TYPE']);
$this->headMeta()->setProperty('og:url', $this->serverUrl().$pageUrl);
$this->headMeta()->setProperty('og:image', $this->serverUrl().$imageSrc);
$this->headMeta()->setProperty('og:description', $description);
$this->headMeta()->setProperty('fb:app_id', $this->socialConfig['FACEBOOK']['APP_ID']);
?>                                         
