<div class="itemsNav">
<span><a href="<?php echo $this->adminPath?>/music/add">New Music</a></span>
</div>
<?php echo $this->render('shared/search.phtml')?>
<table class="admin-dt">
	<thead>
		<tr>
			<th  width="5%">Select</th>
			<th>Music</th>
			<th>Album</th>
			<th width="10%"></th>
			<th width="10%"></th>
			<th width="10%"></th>
			<th width="10%"></th>
		</tr>
	</thead>
	<tbody>
		<?php if (count($this->paginator)): ?>
			<?php foreach ($this->paginator as $music):	?>
			<tr>
				<td>
					<div class="checkboxControl">
						<div class="fieldControl">
						<input name="music_select" type="checkbox" value="<?php echo $this->escape($music->getMusicId()) ?>" />
						</div>
					</div>	
				</td>
				<td><?php echo $this->escape($music->getMusicTitle()) ?></td>
				<td><?php echo $this->escape($music->getAlbum()->getAlbumName()) ?></td>
				<td><a href="<?php echo $this->adminPath?>/music/edit/music_id/<?php echo $this->escape($music->getMusicId()) ?>"><img src="/img/icons/transparent.gif" class="admin_icons view_edit" alt="Edit" title="Click to edit"></a></td>
				<td><a href="<?php echo $this->adminPath?>/music/photo/music_id/<?php echo $this->escape($music->getMusicId()) ?>/has_photo/<?php echo $this->escape(!$music->getHasPhoto()) ?>">
				<?php if ($this->escape($music->getHasPhoto())): ?>				
					<img src="/img/icons/transparent.gif" class="admin_icons view_has_photo" alt="Photo available" title="Photo available | Click to toggle">
				<?php else: ?>
					<img src="/img/icons/transparent.gif" class="admin_icons view_has_no_photo" alt="Photo not available" title="Photo not available | Click to toggle">					
				<?php endif;?></a></td>	
				<td><a href="<?php echo $this->adminPath?>/music/published/music_id/<?php echo $this->escape($music->getMusicId()) ?>/published/<?php echo $this->escape(!$music->getPublished()) ?>">
				<?php if ($this->escape($music->getPublished())): ?>				
					<img src="/img/icons/transparent.gif" class="admin_icons view_publish" alt="Published" title="Published | Click to toggle" />
				<?php else: ?>
					<img src="/img/icons/transparent.gif" class="admin_icons view_unpublish" alt="Not published" title="Not Published | Click to toggle" />					
				<?php endif;?></a></td>							
				<td><a href="<?php echo $this->adminPath?>/music/update-rel/music_id/<?php echo $this->escape($music->getMusicId()) ?>"><img src="/img/icons/transparent.gif" class="admin_icons update_rel" alt="Edit" title="Click to unlock related items"></a></td>
	        </tr>	        
	        <?php endforeach; ?>
	        <tr>
	        	<td ><img class="selectallarrow" src="/img/icons/arrow_ltr.png" alt="With selected:"></td>
	        	<td colspan="6">
	        		<a href="#" onclick="cQuery.markAllRows('music_select'); return false;">Check All</a>&nbsp;|
	        		<a href="#" onclick="cQuery.unMarkAllRows('music_select'); return false;">Uncheck All</a>	        		
	        		<form method="post" class="adminViewForm" action="<?php echo $this->adminPath?>/music/update-many" onsubmit="return cQuery.adminViewFormValidate('music');">
	        			<input type="hidden" id="music_selected" name="music_selected" value="">						
						<select name="select_action" id="select_action">
							<option value="">--Select Action--</option>
							<option value="has_photo__1">Has photo</option>
							<option value="has_photo__0">Has no photo</option>
							<option value="published__1">Publish</option>
							<option value="published__0">Unpublish</option>
						</select>						 
						<button id="submit" class="adminButton" type="submit">
							<span>Update</span>
						</button>
					</form>
				</td>
	        </tr>
	        	
		<?php else: ?>
		<tr>
			<td colspan="7">There are no musics to display</td>
		</tr>
		<?php endif;?>
	</tbody>
</table>
<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'shared/pagination_control.phtml'); ?>
<br/>